"""
Home page of the application
"""
import dash_bootstrap_components as dbc
from dash import html, Output, Input, State, callback, clientside_callback, ClientsideFunction, dcc

from models.home import load_exp_from_db, get_available_applications, get_available_versions, \
    save_file_for_comparison, load_app_wf_from_db, check_type, get_list_structure


def layout():
    """Return the layout for the home page."""
    return html.Div(
        [
            html.H1(
                children='Welcome on the VIP reproducibility dashboard',
                id='home-title',
            ),
            html.Div(
                children=[
                    html.P(
                        'This dashboard allows you to consult, study and compare the results generated by medical '
                        'imagining applications, mainly from the VIP platform. Different types of charts and metrics '
                        'are available to help you understand the results and their differences. For now, two '
                        'applications are explicitly supported: cQUEST and BraTS. You can also upload your own '
                        'results to compare them with adapted charts and metrics based on tabular data.'
                    ),
                ],
            ),

            html.H2(
                children='Based on your own data (from local storage)',
            ),
            html.Div(
                children=[
                    html.Div(
                        children=[
                            dbc.Row(
                                children=[
                                    html.H3('Compare raw results'),
                                    html.Div(
                                        children=[
                                            html.Img(
                                                src='/assets/images/upload_icon.png',
                                                style={'width': '140px', 'height': 'fit-content', 'padding': '10px'},
                                            ),
                                            html.Div(
                                                children=[
                                                    html.P(
                                                        'Upload your own raw results (nifiti or cquest format) to '
                                                        'compare them with adapted charts and metrics.'
                                                    ),
                                                    dbc.Button(
                                                        "Compare your results",
                                                        id="upload-open",
                                                        n_clicks=0,
                                                        style={'width': 'fit-content', 'marginLeft': '10px'},
                                                        className="mr-1"
                                                    ),
                                                    dbc.Modal(
                                                        [
                                                            dbc.ModalHeader(dbc.ModalTitle("Upload your own results")),
                                                            dbc.ModalBody(
                                                                children=[
                                                                    dbc.Row(
                                                                        children=[
                                                                            dbc.Col(
                                                                                children=[
                                                                                    html.P('Select the results format'),
                                                                                    dbc.Select(
                                                                                        id='application-selected-'
                                                                                           'for-upload',
                                                                                        options=[
                                                                                            {
                                                                                                'label': 'cQuest '
                                                                                                         'results '
                                                                                                         '(quest2.txt)',
                                                                                                'value': 'cquest'},
                                                                                            {'label': 'NIfTI files',
                                                                                             'value': 'nifti'},
                                                                                            {'label': 'LCModel results '
                                                                                                      '(.table)',
                                                                                             'value': 'lcmodel'},

                                                                                        ],
                                                                                        value='nifti',
                                                                                        style={'width': '100%'},
                                                                                    ),
                                                                                    html.Br(),
                                                                                    html.P('Select how you want to '
                                                                                           'compare your results'),
                                                                                    dbc.Select(
                                                                                        id=
                                                                                        'data-type-selected-for-upload',
                                                                                        options=[
                                                                                            {
                                                                                                'label': '1 file to 1 '
                                                                                                         'file',
                                                                                                'value': '1-1'},
                                                                                            {
                                                                                                'label': 'x files to y '
                                                                                                         'files '
                                                                                                         '(two zipped '
                                                                                                         'folders)',
                                                                                                'value': 'x-y'},
                                                                                            {
                                                                                                'label': 'x files (one '
                                                                                                         'zipped '
                                                                                                         'folder)',
                                                                                                'value': 'x'},
                                                                                            {
                                                                                                'label': 'x folders ('
                                                                                                         'one zipped '
                                                                                                         'folder with '
                                                                                                         'multiple '
                                                                                                         'sub-folders)',
                                                                                                'value': 'x-folders'},
                                                                                        ],
                                                                                        value='1-1',
                                                                                        style={'width': '100%'},
                                                                                    ),
                                                                                ],
                                                                                className='card-body',
                                                                            ),
                                                                            dbc.Col(
                                                                                children=[
                                                                                    html.P(
                                                                                        'Upload a first file to compare'
                                                                                    ),
                                                                                    html.Br(),
                                                                                    dcc.Upload(
                                                                                        id='upload-data-1',
                                                                                        children=html.Div(
                                                                                            children=[
                                                                                                'Drag and Drop or ',
                                                                                                dbc.NavLink(
                                                                                                    'Select Files')
                                                                                            ],
                                                                                            id='upload-data-1-div'
                                                                                        ),
                                                                                        style={
                                                                                            'width': '100%',
                                                                                            'height': '60px',
                                                                                            'lineHeight': '60px',
                                                                                            'borderWidth': '1px',
                                                                                            'borderStyle': 'dashed',
                                                                                            'borderRadius': '5px',
                                                                                            'textAlign': 'center',
                                                                                            'cursor': 'pointer',
                                                                                        },
                                                                                        multiple=False
                                                                                    ),
                                                                                    dcc.Input(
                                                                                        id='data-1-uuid',
                                                                                        type='hidden',
                                                                                    ),
                                                                                    dcc.Input(
                                                                                        id='data-type-uploaded1',
                                                                                        type='hidden',
                                                                                    ),
                                                                                    html.Br(),
                                                                                    html.Div(
                                                                                        id='output-data-upload-1',
                                                                                        style={'display': 'flex',
                                                                                               'justifyContent':
                                                                                                   'center'}
                                                                                    ),
                                                                                ],
                                                                                className='card-body',
                                                                            ),
                                                                            dbc.Col(
                                                                                children=[
                                                                                    html.P('Upload a second file to '
                                                                                           'compare'),
                                                                                    html.Br(),
                                                                                    dcc.Upload(
                                                                                        id='upload-data-2',
                                                                                        children=html.Div(
                                                                                            children=[
                                                                                                'Drag and Drop or ',
                                                                                                dbc.NavLink(
                                                                                                    'Select Files')
                                                                                            ],
                                                                                            id='upload-data-2-div'
                                                                                        ),
                                                                                        style={
                                                                                            'width': '100%',
                                                                                            'height': '60px',
                                                                                            'lineHeight': '60px',
                                                                                            'borderWidth': '1px',
                                                                                            'borderStyle': 'dashed',
                                                                                            'borderRadius': '5px',
                                                                                            'textAlign': 'center',
                                                                                            'cursor': 'pointer',
                                                                                        },
                                                                                        multiple=False
                                                                                    ),
                                                                                    dcc.Input(
                                                                                        id='data-2-uuid',
                                                                                        type='hidden',
                                                                                    ),
                                                                                    dcc.Input(
                                                                                        id='data-type-uploaded2',
                                                                                        type='hidden',
                                                                                    ),
                                                                                    html.Br(),
                                                                                    html.Div(
                                                                                        id='output-data-upload-2',
                                                                                        style={'display': 'flex',
                                                                                               'justifyContent':
                                                                                                   'center'}
                                                                                    ),
                                                                                ],
                                                                                className='card-body',
                                                                                id='upload-data-2-container',
                                                                            ),
                                                                            dbc.Col(
                                                                                children=[
                                                                                    dbc.Button(
                                                                                        'Compare',
                                                                                        id='compare-btn',
                                                                                        style={'width': '100%'},
                                                                                        className='btn btn-primary',
                                                                                        href='/compare-11?id1=&id2=',
                                                                                        disabled=True,
                                                                                    ),
                                                                                ],
                                                                            ),
                                                                        ],
                                                                        style={'justifyContent': 'center',
                                                                               'gap': '10px'},
                                                                    ),
                                                                ],
                                                                className='card',
                                                                style={'display': 'flex', 'justifyContent': 'center',
                                                                       'gap': '10px'},
                                                            ),
                                                            dbc.ModalFooter(
                                                                dbc.Button(
                                                                    "Close", id="upload-close",
                                                                    className="ms-auto", n_clicks=0
                                                                )
                                                            ),
                                                        ],
                                                        id="upload-modal",
                                                        is_open=False,
                                                    ),
                                                ],
                                                style={'display': 'flex', 'gap': '10px', 'flexDirection': 'column'},
                                            ),
                                        ],
                                        style={'display': 'flex', 'gap': '10px', 'flexDirection': 'row'},
                                    ),
                                ],
                                className='card-body',
                            ),
                        ],
                        className='card',
                        style={'display': 'flex', 'gap': '10px', 'flexDirection': 'column', 'width': '50%'},
                    ),
                    html.Div(
                        children=[
                            dbc.Row(
                                children=[
                                    html.H3('Compare tabular results'),
                                    html.Div(
                                        children=[
                                            html.Img(
                                                src='/assets/images/tabular_icon.png',
                                                style={'width': '140px', 'height': 'fit-content', 'padding': '10px'},
                                            ),
                                            html.Div(
                                                children=[
                                                    html.P(
                                                        'Compare tabular results using your own settings. '
                                                        'Choose axis, metrics and data to compare your results. '
                                                        'You can also share your settings with other users.'
                                                    ),
                                                    dbc.NavLink(
                                                        dbc.Button(
                                                            "Compare tabular results",
                                                            id="compare-tabular-button",
                                                            n_clicks=0,
                                                            style={'width': 'fit-content', 'marginLeft': '10px'},
                                                            className="mr-1"
                                                        ),
                                                        href='visualize-experiment-template',
                                                    )
                                                ],
                                            )
                                        ],
                                        style={'display': 'flex', 'gap': '10px', 'flexDirection': 'row'},
                                    ),
                                ],
                                className='card-body',
                                style={'display': 'flex', 'gap': '10px', 'flexDirection': 'column'},
                            ),
                        ],
                        className='card',
                        style={'display': 'flex', 'gap': '10px', 'flexDirection': 'column', 'width': '50%'},
                    ),
                ],
                style={'display': 'flex', 'gap': '10px', 'flexDirection': 'row'},
            ),
            html.H2(
                children='Based on data from Girder platform (PILoT)',
            ),
            html.Div(
                children=[
                    html.Div(
                        children=[
                            dbc.Row(
                                children=[
                                    html.H3('Study a VIP experiment'),
                                    html.Div(
                                        children=[
                                            html.Img(
                                                src='/assets/images/microscope_icon.png',
                                                style={'width': '125px', 'height': 'fit-content', 'padding': '10px'},
                                            ),
                                            html.Div(
                                                children=[
                                                    html.P(
                                                        'Select an experiment to study its results. Experiment results '
                                                        'are stored on Girder with associated metrics values. '
                                                        'Experiments data are generated by active testing in CI.'
                                                    ),
                                                    dbc.Button(
                                                        "Study experiment",
                                                        id="exec-open",
                                                        n_clicks=0,
                                                        style={'width': 'fit-content', 'marginLeft': '10px'},
                                                        className="mr-1"
                                                    ),
                                                ],
                                            )
                                        ],
                                        style={'width': '100%', 'display': 'flex'},
                                    ),

                                    dbc.Modal(
                                        [
                                            dbc.ModalHeader(dbc.ModalTitle("Select an experiment to study")),
                                            dbc.ModalBody(
                                                children=[
                                                    html.Div(
                                                        children=[
                                                            html.Label(
                                                                children=[
                                                                    "Select an application",
                                                                    html.Br(),
                                                                    dbc.Select(
                                                                        id='select-app-wf',
                                                                        options=[
                                                                            {'label': 'All', 'value': 'all'}
                                                                        ],
                                                                        value='vip',
                                                                        style={'width': '100%'},
                                                                    ),
                                                                ],
                                                            ),
                                                            html.Label(
                                                                children=[
                                                                    "Select a version",
                                                                    html.Br(),
                                                                    dbc.Select(
                                                                        id='select-version-wf',
                                                                        options=[
                                                                            {'label': 'All', 'value': 'all'}
                                                                        ],
                                                                        value='all',
                                                                        style={'width': '100%'},
                                                                    ),
                                                                ],
                                                            ),
                                                            html.Label(
                                                                children=[
                                                                    "Search for an experiment",
                                                                    dbc.Input(
                                                                        id='search-exec',
                                                                        type='text',
                                                                        placeholder='Type here to search',
                                                                        style={'width': '100%'},
                                                                    ),
                                                                ],
                                                            ),
                                                        ],
                                                        style={'display': 'flex', 'gap': '10px',
                                                               'flexDirection': 'column'},
                                                    ),
                                                    # Search bar

                                                    html.Br(),
                                                    html.Div(
                                                        children=[
                                                            # List of experiments (from db)
                                                            dbc.Col(
                                                                className='card',
                                                                id='wf-container',
                                                                style={'flexDirection': 'column', 'maxHeight': '450px'
                                                                    , 'overflowY': 'scroll'},
                                                            ),
                                                        ],
                                                    ),
                                                    html.Div(
                                                        children=[
                                                            # Used for the search bar powered by js (not displayed)
                                                            dbc.Row(
                                                                className='card',
                                                                id='wf-container-hidden',
                                                                style={'display': 'none'},
                                                            ),
                                                        ],
                                                    )

                                                ]
                                            ),
                                            dbc.ModalFooter(
                                                dbc.Button(
                                                    "Close", id="exec-close", className="ms-auto", n_clicks=0
                                                )
                                            ),
                                        ],
                                        id="exec-modal",
                                        is_open=False,
                                    ),
                                ],
                                className='card-body',
                            ),
                        ],
                        className='card',
                        style={'display': 'flex', 'gap': '10px', 'flexDirection': 'column', 'width': '50%'},
                    ),
                    html.Div(
                        children=[
                            dbc.Row(
                                children=[
                                    html.H3('Compare two VIP experiments'),
                                    html.Div(
                                        children=[
                                            html.Img(
                                                src='/assets/images/balance_icon.png',
                                                style={'width': '140px', 'height': 'fit-content', 'padding': '10px'},
                                            ),
                                            html.Div(
                                                children=[
                                                    html.P(
                                                        'Select two experiments to compare their results, and study '
                                                        'similarity metrics.'
                                                    ),
                                                    dbc.Button(
                                                        "Compare experiments",
                                                        id="exp-open",
                                                        n_clicks=0,
                                                        style={'width': 'fit-content', 'marginLeft': '10px'},
                                                        className="mr-1"
                                                    ),
                                                ],
                                            )
                                        ],
                                        style={'width': '100%', 'display': 'flex'},
                                    ),
                                    dbc.Modal(
                                        [
                                            dbc.ModalHeader(dbc.ModalTitle("Select two experiments to compare")),
                                            dbc.ModalBody(
                                                children=[
                                                    html.Div(
                                                        children=[
                                                            html.Label(
                                                                children=[
                                                                    "Select an application",
                                                                    html.Br(),
                                                                    dbc.Select(
                                                                        id='select-app',
                                                                        options=[
                                                                            {'label': 'cQUEST', 'value': 'cquest'},
                                                                            {'label': 'BraTS', 'value': 'brats'},
                                                                        ],
                                                                        value='cquest',
                                                                        style={'width': '100%'},
                                                                    ),
                                                                ],
                                                            ),
                                                            html.Label(
                                                                children=[
                                                                    "Select a version",
                                                                    html.Br(),
                                                                    dbc.Select(
                                                                        id='select-version',
                                                                        options=[
                                                                            {'label': 'All', 'value': 'all'}
                                                                        ],
                                                                        value='all',
                                                                        style={'width': '100%'},
                                                                    ),
                                                                ],
                                                            ),
                                                            html.Label(
                                                                children=[
                                                                    "Search for an experiment",
                                                                    dbc.Input(
                                                                        id='search-exp',
                                                                        type='text',
                                                                        placeholder='Type here to search',
                                                                        style={'width': '100%'},
                                                                    ),
                                                                ],
                                                            ),
                                                        ],
                                                        style={'display': 'flex', 'gap': '10px',
                                                               'flexDirection': 'column'},
                                                    ),
                                                    html.Br(),
                                                    html.Div(
                                                        children=[
                                                            # List of experiments (from db)
                                                            dbc.Col(
                                                                children=[
                                                                    dbc.Row(
                                                                        children=[
                                                                            html.Div(
                                                                                children=[
                                                                                    dbc.RadioItems(
                                                                                        id="repro-execution-radio-1",
                                                                                        style={'width': 'fit-content'},
                                                                                    )
                                                                                ],
                                                                            )
                                                                        ],
                                                                        style={'flexDirection': 'row'},
                                                                    )
                                                                ],
                                                                className='card',
                                                                id='experiment-container-1',
                                                                style={'flexDirection': 'column', 'padding': '5px'},
                                                            ),
                                                            dbc.Col(
                                                                children=[
                                                                    dbc.Row(
                                                                        children=[
                                                                            html.Div(
                                                                                children=[
                                                                                    dbc.RadioItems(
                                                                                        id="repro-execution-radio-2",
                                                                                        style={'width': 'fit-content'},
                                                                                    )
                                                                                ],
                                                                            )
                                                                        ],
                                                                        style={'flexDirection': 'row'},
                                                                    )
                                                                ],
                                                                className='card',
                                                                id='experiment-container-2',
                                                                style={'flexDirection': 'column', 'padding': '5px'},
                                                            ),
                                                        ],
                                                        style={'display': 'flex', 'gap': '10px',
                                                               'flexDirection': 'row'},
                                                    ),
                                                    dbc.Button(
                                                        "Compare",
                                                        id="compare-exp-button",
                                                        n_clicks=0,
                                                        style={'width': 'fit-content'},
                                                        className="mr-1",
                                                        disabled=True
                                                    ),
                                                ]
                                            ),
                                            dbc.ModalFooter(
                                                dbc.Button(
                                                    "Close", id="exp-close", className="ms-auto", n_clicks=0
                                                )
                                            ),
                                        ],
                                        id="exp-modal",
                                        is_open=False,
                                    ),
                                ],
                                className='card-body',
                            ),
                        ],
                        className='card',
                        style={'display': 'flex', 'gap': '10px', 'flexDirection': 'column', 'width': '50%'},
                    ),

                ],
                style={'display': 'flex', 'gap': '10px', 'flexDirection': 'row'},
            ),
        ]
    )


@callback(
    Output('upload-modal', 'is_open'),
    Input('upload-open', 'n_clicks'),
    Input('upload-close', 'n_clicks'),
    State('upload-modal', 'is_open'),
    prevent_initial_call=True
)
def toggle_upload_modal(n1, n2, is_open):
    """Open or close the upload modal"""
    if n1 or n2:
        return not is_open
    return is_open


@callback(
    Output('upload-data-2-container', 'style'),
    Input('data-type-selected-for-upload', 'value'),
)
def update_upload_data_2_container(type_selected):
    """Update the style of the upload data 2 container"""
    if type_selected == 'x' or type_selected == 'x-folders':
        return {'display': 'none'}
    return {'display': 'block'}


@callback(
    Output('compare-btn', 'disabled'),
    Input('compare-btn', 'href'),
    State('data-type-uploaded1', 'value'),
    State('data-type-uploaded2', 'value'),
    State('application-selected-for-upload', 'value'),
    State('data-type-selected-for-upload', 'value'),
    prevent_initial_call=True
)
def update_compare_btn(_, type1, type2, app, type_selected):
    """Update the compare button state depending on the uploaded files and the selected application"""
    # assert that if type_selected is 1-1, type1 and type2 are txt else zip
    if type_selected == '1-1':
        if type1 == 'txt' and type2 == 'txt' and app == 'cquest' or type1 == 'nii' and type2 == 'nii' and app == 'brats' or type1 == 'table' and type2 == 'table' and app == 'lcmodel' or (
                type1 in ['gz', 'nii'] and type2 in ['gz', 'nii'] and app == 'nifti'):
            return False
    if type_selected == 'x-y' and type1 == 'zip' and type2 == 'zip':
        return False
    if type_selected == 'x' and type1 == 'zip':
        return False
    if type_selected == 'x-folders' and type1 == 'zip' and app == 'lcmodel':
        return False
    return True


@callback(
    Output('upload-data-1-div', 'children'),
    Output('data-1-uuid', 'value'),
    Output('compare-btn', 'href', allow_duplicate=True),
    Output('data-type-uploaded1', 'value'),
    Input('upload-data-1', 'contents'),
    State('compare-btn', 'href'),
    State('upload-data-1', 'filename'),
    State('data-type-selected-for-upload', 'value'),
    State('application-selected-for-upload', 'value'),
    prevent_initial_call=True
)
def update_output1(content, href, name, type_selected, app):
    """Update the output of the upload data 1 div"""
    return update_output(content, href, name, 1, type_selected, app)


@callback(
    Output('upload-data-2-div', 'children'),
    Output('data-2-uuid', 'value'),
    Output('compare-btn', 'href', allow_duplicate=True),
    Output('data-type-uploaded2', 'value'),
    Input('upload-data-2', 'contents'),
    State('compare-btn', 'href'),
    State('upload-data-2', 'filename'),
    State('data-type-selected-for-upload', 'value'),
    State('application-selected-for-upload', 'value'),
    prevent_initial_call=True
)
def update_output2(content, href, name, type_selected, app):
    """Update the output of the upload data 2 div"""
    return update_output(content, href, name, 2, type_selected, app)


@callback(
    Output('compare-btn', 'href'),
    Input('application-selected-for-upload', 'value'),
    Input('data-type-selected-for-upload', 'value'),
    State('compare-btn', 'href'),
)
def update_href(app, data_type, href):
    """Update the href of the compare button depending on the selected application and data type of comparison"""
    app_str = 'compare'
    if app == 'nifti':
        app_str = 'compare-nii'
    elif app == 'lcmodel':
        app_str = 'compare-lcmodel'
    data_type_str = '11'
    if data_type == 'x-y':
        data_type_str = 'xy'
    elif data_type == 'x':
        data_type_str = 'x'
    elif data_type == 'x-folders':
        data_type_str = 'x'
    href_end = href.split('?')[1]
    href = app_str + '-' + data_type_str + '?' + href_end
    return href


def update_output(content, href, name, data_id, data_type, app):
    """Update the output of the upload data div"""
    if check_type(data_type, name, app):
        file_extension = name.split('.')[-1]
        if file_extension in ['txt', 'zip', 'nii', 'table'] or (
                name.split('.')[-2] == 'nii' and file_extension == 'gz'):
            # save the file in the server
            flatten = False if data_type == 'x-folders' else True
            uuid = save_file_for_comparison(content, name, flatten)
            # get olds values
            id1 = 'id1=' + href.split('id1=')[1].split('&id2=')[0]
            id2 = 'id2=' + href.split('id2=')[1]
            # update the href
            if data_id == 1:
                id1 = 'id1=' + str(uuid)
            else:
                id2 = 'id2=' + str(uuid)
            href_begin = href.split('?')[0]
            href = href_begin + '?' + id1 + '&' + id2
            return html.Div([
                html.P('File uploaded: ' + name),
            ]), str(uuid), href, file_extension
        return html.Div([
            'Wrong file type, please upload a .txt file'
        ]), None, href, None
    return html.Div([
        'Wrong file type, please upload a file according to the selected application and data type',
    ]), None, href, None


@callback(
    Output("exec-modal", "is_open"),
    Output("wf-container-hidden", "children", allow_duplicate=True),
    Output("select-app-wf", "options"),
    [Input("exec-open", "n_clicks"), Input("exec-close", "n_clicks")],
    [State("exec-modal", "is_open")],
    prevent_initial_call=True
)
def toggle_modal_workflows(n1, n2, is_open):
    """Open or close the workflows modal"""
    if n1 or n2:
        wf_list = load_exp_from_db()
        wf_data = get_list_structure(wf_list, '/visualize-experiment')
        applications = get_available_applications()
        options = [{'label': app['name'], 'value': app['id']} for app in applications]
        options.insert(0, {'label': 'All', 'value': 'all'})
        return not is_open, wf_data, options

    return is_open, [], []


@callback(
    Output("repro-execution-radio-1", "options", allow_duplicate=True),
    Output("repro-execution-radio-2", "options", allow_duplicate=True),
    Input("select-version", "value"),
    State("select-app", "value"),
    prevent_initial_call=True
)
def filter_exp(version_id, app_id):
    """Filter the experiments depending on the selected application and version"""
    exp_list = load_exp_from_db()
    new_exp_list = []
    if version_id != 'all':
        for exp in exp_list:
            if int(exp['version_id']) == int(version_id) and int(exp['application_id']) == int(app_id.split('/-/')[0]):
                new_exp_list.append(exp)
    else:
        for exp in exp_list:
            if int(app_id.split('/-/')[0]) == exp['application_id']:
                new_exp_list.append(exp)

    options = [{'label': exp['application_version'] + " - " + exp['name'], 'value': str(exp['id']) + '/-/' +
               exp['application_name']} for exp in new_exp_list]

    return options, options


@callback(
    Output("wf-container", "children", allow_duplicate=True),
    Input("select-version-wf", "value"),
    prevent_initial_call=True
)
def filter_wf(version_id):
    """Filter the workflows depending on the selected version"""
    wf_list = load_exp_from_db()
    new_wf_list = []
    if version_id != 'all':
        for wf in wf_list:
            if int(wf['version_id']) == int(version_id):
                new_wf_list.append(wf)
    else:
        new_wf_list = wf_list

    wf_data = get_list_structure(new_wf_list, '/visualize-experiment')

    return wf_data


@callback(
    Output("exp-modal", "is_open"),
    Output("repro-execution-radio-1", "options", allow_duplicate=True),
    Output("repro-execution-radio-2", "options", allow_duplicate=True),
    Output("select-app", "options"),
    Output("select-app", "value"),
    [Input("exp-open", "n_clicks"), Input("exp-close", "n_clicks")],
    [State("exp-modal", "is_open")],
    prevent_initial_call=True
)
def toggle_modal_exp(n1, n2, is_open):
    """Open or close the experiments modal"""
    if n1 or n2:
        exp_list = load_exp_from_db()
        exp_options = [{'label': exp['application_version'] + " - " + exp['name'], 'value': str(exp['id']) + '/-/' +
                                                                                            exp['application_name']} for
                       exp in exp_list]
        applications = get_available_applications()
        options = [{'label': app['name'], 'value': str(app['id']) + '/-/' + app['name']} for app in applications]
        return not is_open, exp_options, exp_options, options, options[0]['value']

    return is_open, [], [], [], []


@callback(
    Output("select-version", "options"),
    Output("repro-execution-radio-1", "options", allow_duplicate=True),
    Output("repro-execution-radio-2", "options", allow_duplicate=True),
    [Input("select-app", "value")],
    prevent_initial_call=True
)
def update_version_dropdown(app_id):
    """Update the version dropdown depending on the selected application"""
    exp_list, options = load_experiments(app_id)
    new_exp_list = []
    if app_id != 'all':
        for exp in exp_list:
            if int(exp['application_id']) == int(app_id.split('/-/')[0]):
                new_exp_list.append(exp)
    else:
        new_exp_list = exp_list

    exp_options = [{'label': exp['application_version'] + " - " + exp['name'], 'value': str(exp['id']) + '/-/' +
                                                                                        exp['application_name']} for exp
                   in new_exp_list]

    return options, exp_options, exp_options


@callback(
    Output("select-version-wf", "options"),
    Output("wf-container", "children", allow_duplicate=True),
    [Input("select-app-wf", "value")],
    prevent_initial_call=True
)
def update_wf_version_dropdown(app_id):
    """Update the version dropdown depending on the selected application"""
    wf_list, options = load_experiments(app_id)
    new_wf_list = []
    if app_id != 'all':
        for wf in wf_list:
            if int(wf['application_id']) == int(app_id):
                new_wf_list.append(wf)
    else:
        new_wf_list = wf_list

    wf_data = get_list_structure(new_wf_list, '/visualize-experiment')
    return options, wf_data


def load_experiments(app_id):
    """
    Load the experiments and the options depending on the selected application
    """
    versions = get_available_versions(app_id)
    options = [{'label': version['number'], 'value': version['id']} for version in versions]
    options.sort(key=lambda x: x['label'])
    options.insert(0, {'label': 'All', 'value': 'all'})
    return load_exp_from_db(), options


clientside_callback(
    ClientsideFunction(
        namespace="clientside",
        function_name="search_exp",
    ),
    Output("wf-container", "children", allow_duplicate=True),
    [Input("search-exec", "value"), Input("wf-container-hidden", "children")],
    prevent_initial_call=True
)


@callback(
    Output("compare-exp-button", "disabled"),
    Output("compare-exp-button", "href"),
    [Input("repro-execution-radio-1", "value"), Input("repro-execution-radio-2", "value")],
    prevent_initial_call=True
)
def toggle_compare_button(exp1, exp2):
    """Toggle the compare button depending on the selected experiments"""
    application_name1 = None
    application_name2 = None
    if exp1 is not None and exp2 is not None:
        application_name1 = exp1.split('/-/')[1]
        application_name2 = exp2.split('/-/')[1]

    if exp1 is not None and exp2 is not None and application_name1 == application_name2:
        begin_href = '/compare-exp-'
        if application_name1.lower() == 'brats':
            begin_href += 'brats'
        elif application_name1.lower() == 'cquest':
            begin_href += 'cquest'
        return False, begin_href + '?exp1=' + str(exp1.split('/-/')[0]) + '&exp2=' + str(exp2.split('/-/')[0])
    return True, '#'


@callback(
    Output("repro-wf-radio-1", "options", allow_duplicate=True),
    Output("repro-wf-radio-2", "options", allow_duplicate=True),
    Input("select-vip-app-wf", "value"),
    prevent_initial_call=True
)
def update_upload_options(app_id):
    """Update the options of the upload select"""
    wf_list = load_app_wf_from_db(app_id)
    options = [
        {'label': wf['name'] + " (" + wf['application_version'] + ")",
         'value': str(wf['id']) + '/-/' + wf['application_name']}
        for wf in wf_list]
    return options, options


@callback(
    Output("compare-upload-button", "disabled"),
    Output("compare-upload-button", "href"),
    [Input("repro-wf-radio-1", "value"),
     Input("repro-wf-radio-2", "value"),
     Input("select-vip-app-wf", "value"),
     Input("select-vip-app-wf", "options")],
    prevent_initial_call=True
)
def toggle_upload_compare_button(wf1, wf2, app_id, options):
    """Toggle the compare button depending on the selected workflows"""
    if wf1 is not None and wf2 is not None:
        application_name = None
        for option in options:
            if int(option['value']) == int(app_id):
                application_name = option['label'].split(' ')[0].lower()
        extension = ''
        if application_name == 'nifti':
            extension = 'compare-nii-11'
        elif application_name == 'cquest':
            extension = 'compare-xy'
        return False, extension + '?id1=' + str(wf1.split('/-/')[0]) + '&id2=' + str(wf2.split('/-/')[0])
    return True, '#'
